### PR TITLE
Register swagger UI and JSON as named resources

### LINKED ISSUE #65: Add ability to register swagger page and documentation as named resources
Hello.

It is more a wishlist than a bug, but it will be useful to have the swagger resources registered as [named resource](https://docs.aiohttp.org/en/stable/web_quickstart.html#reverse-url-constructing-using-named-resources) (like `swagger.doc` and `swagger.spec` or something similar) so that we can retrieve them more easily.

### PR DESCRIPTION
**Pull request by alvarolopez**
Fixes #65

### CODE REVIEW

**Comment by alvarolopez** [comment]
Cool thanks for including it.

**Comment by alvarolopez** [comment]
By the way, any ETA for the next release?

Thanks!

**Comment by maximdanilchenko** [comment]
@alvarolopez, will release it this week.

**Comment by maximdanilchenko** [comment]
@alvarolopez Version 2.2.0 is on PyPI now!

**Pull request merged**
